Bump compileSdkVersion to 31
nextcloud/android-library pull request #779
Opened 2021-12-09 07:43 UTC by tobiasKaminsky

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

2021-12-09 09:54 UTC, AlvaroBrey approved these changes

2021-12-09 09:54 UTC, AlvaroBrey requested changes
Lint and all tests failing

2021-12-10 06:19 UTC, tobiasKaminsky commented
> Lint and all tests failing

Lint fails due to upgrade of gradle and the other fails due to the mTime changes, which will be fixed in #780

2021-12-10 07:01 UTC, tobiasKaminsky commented
/rebase

2021-12-10 08:23 UTC, AlvaroBrey approved these changes

2021-12-10 08:23 UTC, merged